"""Delivery pack rendering — layered governed context per team (spec §4–§8).

Level 2 (team pack), Level 3 (story pack) and Level 4 (thin task pack) are
rendered here as pure functions; the engine owns storage, versioning,
provenance and phase transitions. Task packs reference canonical artifacts by
version in `context.json` — they never copy architecture.md.

`AGENTS.md` carries the s7-managed marker line: publication refuses to
overwrite an AGENTS.md that lacks it (someone else's file), and developers
can see at a glance that the file is generated, not hand-written.
"""

from __future__ import annotations

from s7_delivery.factory import layers
from s7_delivery.factory.architecture import dependency_map, team_slug
from s7_delivery.factory.artifact_export import (
    render_acceptance_criteria_md,
    render_agents_md,
    story_folder_name,
)

S7_MARKER = "<!-- s7-managed: generated by the S7 Delivery Control Centre; do not hand-edit -->"

TEAM_FILES = (
    "README.md",
    "team-delivery-pack.md",
    "AGENTS.md",
    "assigned-stories.json",
    "team-dependencies.json",
    "test-strategy.md",
    "rollback-guidance.md",
    "git-workflow.md",
    "code-conventions.md",
    "ui-guidelines.md",
    "db-conventions.md",
    "ui/app.css",
    "ui/layout.html",
    "workspace-manifest.json",
)

# Delivery-profile files a team pack is rendered from (the Standards layer
# plus the identity the UI standards read). The engine pins their versions on
# the pack record (`pins`), so a later profile edit shows as a stale pack
# rather than silently changing what the next publish carries.
PINNED_LAYER_FILES: tuple[str, ...] = (
    "git-workflow", "code-conventions", "ui-guidelines", "db-conventions",
    "ui-starter-css", "ui-layout-thymeleaf", "ui-layout-jinja", "identity",
)

# The same marker in CSS-comment form, for the starter stylesheet.
S7_MARKER_CSS = "/* s7-managed: generated by the S7 Delivery Control Centre; do not hand-edit */"

# Which starter layout a repository's stack receives; an unknown stack gets
# the Thymeleaf one (the seeded MapleSure portals are Spring applications).
LAYOUT_BY_STACK = {"maven": "ui-layout-thymeleaf", "pytest": "ui-layout-jinja"}

# The one stack-aware line of the code conventions: the suite command and the
# naming style a repository of that stack already uses. Every rule in the
# standard itself is stack-neutral, and rule 1 defers to the repository.
STACK_LINES = {
    "maven": (
        "This repository is Java on Maven: run the full suite with `mvn test`,"
        " follow the naming the JDK and this codebase already use"
        " (`camelCase` methods and fields, `PascalCase` types,"
        " `UPPER_SNAKE_CASE` constants), and prefer the JDK and the"
        " dependencies already on the classpath before adding another."
    ),
    "pytest": (
        "This repository is Python: run the full suite with `pytest`, follow"
        " PEP 8 as this codebase already applies it (`snake_case` functions"
        " and variables, `PascalCase` classes, `UPPER_SNAKE_CASE` constants),"
        " and prefer the standard library and the packages already in the"
        " requirements before adding another."
    ),
    "": (
        "The repository's stack is not recorded on this pack, so take the"
        " naming style, the test command and the project layout from the"
        " files already in it rather than from any default."
    ),
}

# The developer phrases the coding agent acts on. Anything else the developer
# says is ordinary work in the working tree — never a commit, never a push.
PHRASE_START = "start working on <story-id>"
PHRASE_PLAN = "plan the next criterion"
PHRASE_BUILD = "build the plan"
PHRASE_COMMIT = "commit the changes"
PHRASE_PUSH = "development completed: please push the code"

STORY_FILES = ("story.md", "acceptance-criteria.md", "dependencies.json",
               "story-context.json")

TASK_FILES = ("task.md", "context.json", "test-plan.md", "task-evidence.json")


def pack_id_for(team: str) -> str:
    return f"PACK-{team_slug(team)}"


def branch_name(run_id: str, team: str) -> str:
    """Fresh, disposable context branch — unique per run and team, and never
    a default branch name by construction."""
    return f"s7/{run_id.lower()}-{team_slug(team)}"


# --- Level 3: story pack ----------------------------------------------------


def render_story_pack(story: dict, *, plan_version: int,
                      architecture_version: int) -> dict[str, object]:
    return {
        "story.md": render_agents_md(story),
        "acceptance-criteria.md": render_acceptance_criteria_md(story),
        "dependencies.json": {
            "story_id": story["story_id"],
            "depends_on": story.get("dependencies", []),
        },
        "story-context.json": {
            "story_id": story["story_id"],
            "epic_id": story.get("epic_id", ""),
            "plan_version": plan_version,
            "architecture_version": architecture_version,
            "accountable_team": story.get("accountable_team", ""),
            "repository": story.get("target_repository", ""),
            "acceptance_criteria": [
                ac["ac_id"] for ac in story.get("acceptance_criteria", [])
            ],
        },
    }


# --- Level 4: thin task pack ------------------------------------------------


def render_task_pack(task: dict, story: dict, *, plan_version: int,
                     architecture_version: int,
                     team_pack_version: int) -> dict[str, object]:
    acs = [ac["ac_id"] for ac in story.get("acceptance_criteria", [])]
    task_md = "\n".join([
        f"# {task['task_id']} — {task.get('summary', '')}",
        "",
        f"Story: {task['story_id']} — {story.get('title', '')}",
        f"Accountable team: {task.get('accountable_team', '')}",
        "",
        "## Goal",
        story.get("purpose", ""),
        "",
        "## Acceptance criteria in scope",
        *[f"- {ac_id}" for ac_id in acs],
        "",
        "Canonical context: see `context.json` — architecture and plan are"
        " referenced by version, not copied.",
    ]) + "\n"
    test_plan = "\n".join([
        f"# Test plan — {task['task_id']}",
        "",
        "Every acceptance criterion must have linked executable evidence.",
        "",
        *[f"- [ ] {ac['ac_id']}: covered by a test that fails before the"
          f" change and passes after ({ac['text']})"
          for ac in story.get("acceptance_criteria", [])],
    ]) + "\n"
    return {
        "task.md": task_md,
        "context.json": {
            "task_id": task["task_id"],
            "story_id": task["story_id"],
            "plan_version": plan_version,
            "architecture_version": architecture_version,
            "team_pack_version": team_pack_version,
            "acceptance_criteria": acs,
            "dependencies": task.get("dependencies", []),
        },
        "test-plan.md": test_plan,
        "task-evidence.json": {
            "task_id": task["task_id"],
            "status": task.get("status", "not_started"),
            "commit_ref": task.get("commit_ref", ""),
            "pr_ref": task.get("pr_ref", ""),
            "ci_status": task.get("ci_status", ""),
        },
    }


# --- Level 2: team pack -----------------------------------------------------


def _story_rows(stories: list[dict]) -> tuple[str, str]:
    """(branch_rows, note_rows): the per-story lines the git and database
    standards list — one working branch and one story note per story."""
    branch_rows = "\n".join(
        f"- {s['story_id']}: `feature/{s['story_id'].lower()}-<short-slug>`"
        f" (e.g. `feature/{story_folder_name(s).lower()}`)"
        for s in stories
    )
    note_rows = "\n".join(
        f"- {s['story_id']}: `docs/delivery/{s['story_id']}.md`" for s in stories
    )
    return branch_rows, note_rows


def render_git_workflow_md(
    *, run_id: str, team: str, stories: list[dict],
    default_branch: str = "main",
) -> str:
    """Git rules for the workspace, made concrete: real branch names and
    story ids, the five developer phrases a coding agent acts on, the
    per-criterion loop that plans one criterion into the story note for the
    developer to edit, builds what they left there, and has them observe it
    working before the next is planned, the story-owned-files rule that
    keeps parallel stories from conflicting on merge, and the exact
    "development completed" protocol run before any push. The text is the `git-workflow`
    standard of the run's delivery profile; this renderer supplies the run's
    own names and prepends the s7-managed marker. Published to
    `.s7/shared/git-workflow.md`."""
    branch_rows, note_rows = _story_rows(stories)
    body = layers.standard(
        "git-workflow",
        team=team,
        repository=next((s.get("target_repository", "") for s in stories), ""),
        context_branch=branch_name(run_id, team),
        default_branch=default_branch,
        branch_rows=branch_rows,
        note_rows=note_rows,
        phrase_start=PHRASE_START,
        phrase_plan=PHRASE_PLAN,
        phrase_build=PHRASE_BUILD,
        phrase_commit=PHRASE_COMMIT,
        phrase_push=PHRASE_PUSH,
    )
    return S7_MARKER + "\n" + body + "\n"


def render_db_conventions_md(*, stories: list[dict],
                             default_branch: str = "main") -> str:
    """Schema, migration, config-fragment and seed-data rules — the
    `db-conventions` standard with the run's default branch and story note
    rows. Published to `.s7/shared/db-conventions.md`."""
    _, note_rows = _story_rows(stories)
    body = layers.standard(
        "db-conventions", default_branch=default_branch, note_rows=note_rows,
    )
    return S7_MARKER + "\n" + body + "\n"


# Design tokens — the token *names* are the contract every page reads
# (`var(--ms-red)`); the *values* come from the delivery profile's identity
# file, so a tenant is restyled in one place and the Control Centre's own
# palette (apps/control/web/src/theme.css) stays the default. Pairings marked
# AA are the ones a contrast test should pin.
_PALETTE_TOKENS = (
    ("ink", "--ms-ink"),
    ("muted", "--ms-muted"),
    ("bg", "--ms-bg"),
    ("surface", "--ms-surface"),
    ("surface-2", "--ms-surface-2"),
    ("border", "--ms-border"),
    ("border-strong", "--ms-border-strong"),
    ("primary", "--ms-red"),
    ("primary-dark", "--ms-red-dark"),
    ("primary-pale", "--ms-red-pale"),
    ("success", "--ms-green"),
    ("success-pale", "--ms-green-pale"),
    ("warning-text", "--ms-amber-text"),
    ("warning-pale", "--ms-amber-pale"),
)
_TOKEN_USES = {
    "--ms-ink": "headings, body text on light surfaces (AA on --ms-bg and --ms-surface)",
    "--ms-muted": "help text, secondary labels (AA on --ms-surface)",
    "--ms-bg": "page background",
    "--ms-surface": "cards, form panels",
    "--ms-surface-2": "table stripes, read-only fields",
    "--ms-border": "hairlines, input borders",
    "--ms-border-strong": "focused-but-not-active borders (3:1 on --ms-surface)",
    "--ms-red": "primary action, brand mark, focus ring (AA as text on white)",
    "--ms-red-dark": "primary hover/active, link text",
    "--ms-red-pale": "error banner background (with --ms-red-dark text)",
    "--ms-green": "success text and icons",
    "--ms-green-pale": "success banner background",
    "--ms-amber-text": "warning text",
    "--ms-amber-pale": "warning banner background",
    "--ms-radius-sm": "inputs, buttons",
    "--ms-radius-md": "cards, banners",
    "--ms-space": "spacing unit — use multiples: 8, 16, 24, 32, 48",
    "--ms-font": "one family, system fallback, nothing fetched at runtime",
}


def ui_tokens(identity: dict | None = None) -> list[tuple[str, str, str]]:
    """(token, value, use) rows from the identity file — the active
    profile's unless one is passed."""
    identity = identity if identity is not None else layers.structured("identity")
    try:
        palette = identity["palette"]
        rows = [(tok, palette[key], _TOKEN_USES[tok]) for key, tok in _PALETTE_TOKENS]
        rows += [
            ("--ms-radius-sm", identity["radius"]["sm"], _TOKEN_USES["--ms-radius-sm"]),
            ("--ms-radius-md", identity["radius"]["md"], _TOKEN_USES["--ms-radius-md"]),
            ("--ms-space", identity["space"], _TOKEN_USES["--ms-space"]),
            ("--ms-font", identity["font"], _TOKEN_USES["--ms-font"]),
        ]
    except KeyError as exc:
        raise layers.LayerError(f"identity file is missing {exc.args[0]!r}") from exc
    return rows


# The default profile's tokens — the Control Centre's own palette — resolved
# against the committed identity file explicitly, never an active profile.
UI_TOKENS: tuple[tuple[str, str, str], ...] = tuple(
    ui_tokens(layers.structured("identity", layers.LAYERS_ROOT))
)


def css_tokens(identity: dict | None = None) -> str:
    """The token declarations of the `:root` block, one per line."""
    return "\n".join(f"  {n}: {v};" for n, v, _ in ui_tokens(identity))


def render_ui_guidelines_md(*, team: str, stories: list[dict]) -> str:
    """Developer-facing UI rules for every page a story adds or changes.
    Deterministic and stack-neutral (server-rendered templates or a component
    framework alike); the text is the `ui-guidelines` standard and the tokens
    are the identity file's, so a delivered page reads as the tenant's, not
    as a framework default. Published to `.s7/shared/ui-guidelines.md`."""
    identity = layers.structured("identity")
    tokens = ui_tokens(identity)
    ui_stories = [
        s for s in stories
        if any(k in (s.get("target_component") or "").lower()
               for k in ("ui", "portal", "front", "web", "page"))
    ]
    scope = (
        "Stories in this pack that ship a page: "
        + ", ".join(s["story_id"] for s in ui_stories)
        + "."
        if ui_stories else
        "No story in this pack names a UI component; these rules still bind"
        " any page a story happens to touch."
    )
    body = layers.standard(
        "ui-guidelines",
        team=team,
        scope_line=scope,
        css_block=":root {\n" + css_tokens(identity) + "\n}",
        token_rows="\n".join(f"| `{n}` | `{v}` | {use} |" for n, v, use in tokens),
        organisation=identity["organisation"],
        short_mark=identity["short_mark"],
        product_line=identity["product_line"],
        synthetic_domain=identity["synthetic_domain"],
    )
    return S7_MARKER + "\n" + body + "\n"


def render_code_conventions_md(*, team: str, stories: list[dict],
                               stack: str | None = None) -> str:
    """How the application code itself is written — the gap the UI guidelines
    and DB conventions left open. Deterministic and stack-neutral in its
    rules; only the opening line names the repository's stack, and the first
    rule defers to the repository's own conventions wherever they disagree,
    because S7 has never seen the codebase and the repository has. Published
    to `.s7/shared/code-conventions.md`."""
    stack_line = STACK_LINES.get(stack or "", STACK_LINES[""])
    scope = (
        "Every story in this pack follows it: "
        + ", ".join(s["story_id"] for s in stories) + "."
        if stories else
        "It binds every story published in this pack."
    )
    body = layers.standard(
        "code-conventions",
        team=team,
        stack_line=stack_line,
        scope_line=scope,
    )
    return S7_MARKER + "\n" + body + "\n"


def layout_file_for(stack: str | None) -> str:
    return LAYOUT_BY_STACK.get(stack or "", "ui-layout-thymeleaf")


def render_ui_starter_files(*, stack: str | None = None) -> dict[str, str]:
    """The starter stylesheet and shared page layout a story copies in rather
    than building its own shell: `ui/app.css` from the `ui-starter-css`
    standard with the identity tokens, `ui/layout.html` from the layout
    standard for the repository's stack (Thymeleaf for maven, Jinja2 for
    pytest, Thymeleaf when the stack is unknown). Published under
    `.s7/shared/ui/`."""
    identity = layers.structured("identity")
    names = {
        "organisation": identity["organisation"],
        "short_mark": identity["short_mark"],
        "product_line": identity["product_line"],
    }
    css = layers.standard("ui-starter-css", css_tokens=css_tokens(identity))
    layout = layers.standard(layout_file_for(stack), **names)
    return {
        "ui/app.css": S7_MARKER_CSS + "\n" + css + "\n",
        "ui/layout.html": S7_MARKER + "\n" + layout + "\n",
    }


def render_team_agents_md(team: str, stories: list[dict], tasks: list[dict],
                          *, architecture_version: int,
                          assignments: dict[str, str] | None = None,
                          assets: list | None = None) -> str:
    """Developer/coding-agent guidance (spec §14). The developer owns
    implementation; a coding assistant may help — S7 provides the context."""
    assignments = assignments or {}
    assets = layers.assets() if assets is None else assets
    story_ids = [s["story_id"] for s in stories]
    components = sorted(
        {s.get("target_component", "") for s in stories if s.get("target_component")}
    )
    assets_section: list[str] = []
    if assets:
        assets_section = [
            "## Project Assets",
            "Artifacts this project supplies, published verbatim under"
            " `.s7/assets/`. They are **reference material, not source**:"
            " copy what you need into the story's own files — a baseline"
            " schema becomes your migration, a contract becomes your"
            " generated client. Never edit a file under `.s7/assets/`;"
            " S7 overwrites that directory on the next publish.",
            "",
            *[f"- `.s7/assets/{a.dest}` — {a.summary or a.title}" for a in assets],
            "",
            "Where an asset disagrees with this repository, **the repository"
            " wins** — the same rule `code-conventions.md` opens with. S7 has"
            " never seen your code; the neighbouring files have.",
            "",
        ]
    lines = [
        S7_MARKER,
        f"# {team} — delivery context",
        "",
        "## Application Context",
        f"MapleSure group benefits. Architecture v{architecture_version} in"
        " `.s7/shared/architecture.md` is canonical for boundaries and data"
        " flow; the repository's own `architecture.md` stays authoritative"
        " for local detail.",
        "",
        "## Current Delivery Context",
        *[f"- {s['story_id']}: {s.get('title', '')}" for s in stories],
        *[f"- {t['task_id']} → {t['story_id']}: {t.get('summary', '')}"
          for t in tasks],
        "",
        "## Story Assignments",
        "Assignment is a human decision made in the S7 Control Centre —"
        " canonical copy in `.s7/shared/assigned-stories.json`.",
        *[
            f"- {s['story_id']} ({s.get('title', '')}): "
            + (f"assigned to {assignments[s['story_id']]}"
               if assignments.get(s["story_id"]) else "unassigned")
            for s in stories
        ],
        "",
        '## Coding Agent: "What is assigned to me?"',
        "When a developer asks what they should work on: read"
        " `.s7/shared/assigned-stories.json`, match their name against"
        " `assigned_to`, then open `.s7/stories/<story>/` for that story —"
        " `story.md` for context, `acceptance-criteria.md` for the checklist,"
        " and `.s7/tasks/<task>/` for the executable task packs. Summarise"
        " the story and its acceptance criteria before implementing, plan them"
        " one acceptance criterion at a time under Build Discipline"
        " below, and implement"
        " only within Allowed Components under the Engineering Rules. If no"
        " story carries their name, say so — never guess an assignment.",
        "",
        "## Git Workflow",
        "All branch, commit and push rules live in"
        " `.s7/shared/git-workflow.md`. The developer owns every commit and"
        " push, and edits every plan before it is built; act on exactly five"
        " phrases:",
        f'- "{PHRASE_START}" — branch, list the criteria in build order, lay'
        " the red baseline, ask the blocking questions. **Plan nothing and"
        " write no code.**",
        f'- "{PHRASE_PLAN}" — write the code plan for *one* criterion into'
        " the story note and stop, so the developer can change it.",
        f'- "{PHRASE_BUILD}" — re-read that section as the developer left it,'
        " build exactly that until its test and the full suite are green,"
        " then hand them a way to see it working and stop.",
        f'- "{PHRASE_COMMIT}" — commit what was reviewed: red baseline first,'
        " implementation second, story id in every message.",
        f'- "{PHRASE_PUSH}" — run that file\'s push checklist in order and'
        " refuse to push if any step fails.",
        "",
        "## Build Discipline",
        "A story is delivered **one acceptance criterion at a time**, and"
        " each criterion goes plan → edit → build → see it working before"
        " the next one is planned. On the plan phrase, write that **one**"
        " criterion's plan into its section of the story note"
        " (`docs/delivery/<story-id>.md`): the criterion verbatim, the S7"
        " skeleton test that proves it, the **code plan** (every function,"
        " module, template and config key to create or change, each with why"
        " *this* criterion needs it, named against code that actually"
        " exists) and how the developer will see it working. Then stop —"
        " **that section is the contract and the developer owns it**, so"
        " they may rewrite any part of it. On the build phrase, re-read the"
        " section **as they left it** and build what it now says, never what"
        " was proposed; if an edit cannot be implemented as written, say why"
        " and stop. Work inside one criterion is continuous, so nobody is"
        " asked to approve each function. Then hand them the page, command"
        " or query that shows the criterion working, wait for what they"
        " actually observed, record it in that section, tick it and stop."
        " Later criteria are planned when their turn comes, never in"
        " advance. A criterion nobody looked at is not done, and a whole"
        " story is never generated in one pass. See the"
        f' "{PHRASE_PLAN}" and "{PHRASE_BUILD}" sections of'
        " `.s7/shared/git-workflow.md`.",
        "",
        "## Reporting",
        "Write every handoff for the developer, not for the process"
        " (*How to report back* in `.s7/shared/git-workflow.md`). Lead with"
        " the state — which story, which phase, what their next word is —"
        " then what is on disk as a short list, then the questions. Show the"
        " branch, files, criteria and test results rather than narrating"
        " them, and keep this pack's own vocabulary out of it: explain a"
        " refusal by what it breaks, never by a rule number, since the"
        " developer has not read these files. Write each open question as a"
        " decision they can answer in a word — one line of context, two or"
        " three lettered options, your recommendation and why, and who owns"
        " the answer where it is the story author's rather than theirs —"
        " with the blocking ones first. Never call an unproven result"
        " verified: a build that did not compile is not a red baseline, and"
        " a change nobody ran is not working.",
        "",
        "## Story-Owned Files",
        "Never edit a shared file (`README.md`, `architecture.md`, the shared"
        " application config, CI workflows) on a story branch — that is how"
        " parallel stories conflict on merge. Story notes go in"
        " `docs/delivery/<story-id>.md`; feature-flag defaults live in code."
        " See the *Story-owned files* section of"
        " `.s7/shared/git-workflow.md`.",
        "",
        "## Code Rules",
        "How the code itself is written is governed by"
        " `.s7/shared/code-conventions.md`, and a criterion is met only when"
        " its test passes **and** the code follows it. Read it before the"
        " first line. Its first rule outranks the rest: **open the"
        " neighbouring files and follow what this repository already does** —"
        " naming, layering, how errors travel, how tests are arranged — and"
        " where the repository disagrees with the standard, the repository"
        " wins. Then: one job per function, early returns instead of deep"
        " nesting, never swallow a failure, validate every input once at the"
        " edge, log identifiers and never contents, comments say *why*, and"
        " no dead code, no speculative abstraction, no invented library"
        " calls, no secrets. Reuse what is already here before adding"
        " anything, and a new dependency is a team decision, not a story's"
        " convenience.",
        "",
        "## Architecture Rules",
        "Respect the integration boundaries in"
        " `.s7/shared/architecture.md`; consume other applications only"
        " through their published interfaces. Do not introduce a new"
        " architectural pattern inside a story.",
        "",
        "## Engineering Rules",
        "See `.s7/shared/engineering-rules.md` — scope discipline,"
        " test-first, traceability, no self-approval.",
        "Reference the story id (and task id where relevant) in every commit"
        " message — e.g. `US-1: add sign-in form`. The Control Centre reads"
        " progress from the repository by exactly this convention.",
        "",
        "## Acceptance Criteria",
        "Per story under `.s7/stories/<story>/acceptance-criteria.md`."
        " Every criterion needs linked executable evidence.",
        "",
        "## Testing Rules",
        "Write the failing test first; record the red baseline; a criterion"
        " without a test is not done.",
        "",
        "## UI Rules",
        "Every page this team adds or changes follows"
        " `.s7/shared/ui-guidelines.md` — MapleSure tokens, page anatomy,"
        " the five states every page must render, WCAG AA, and the"
        " screenshots the pull request must carry. Start from the shared"
        " layout and stylesheet under `.s7/shared/ui/` (`layout.html`,"
        " `app.css`), never from a framework default. A page that works but"
        " ignores it is not done.",
        "",
        "## Data Rules",
        "Every story that touches persistence follows"
        " `.s7/shared/db-conventions.md` — one forward-only migration per"
        " story, named for it and never edited after merge; a config"
        " fragment per story, never an edit to the shared config; synthetic"
        " seed data in a dev profile only.",
        "",
        *assets_section,
        "## Scope Boundaries",
        f"This pack covers {', '.join(story_ids)} only.",
        "",
        "## Allowed Components",
        *[f"- {c}" for c in components],
        "- associated tests",
        "",
        "## Out-of-Scope Components",
        "Everything not listed above — a change outside scope needs a new"
        " ticket, not a bigger diff.",
        "",
        "## Security / Compliance Constraints",
        "Synthetic data only; no PII in code, fixtures or logs; no shared"
        " credentials.",
        "",
        "## Rollback Expectations",
        "Feature flags and the story rollback plans in"
        " `rollback-guidance.md` must be wired before release.",
        "",
        "## Completion Conditions",
        "All acceptance criteria evidenced by passing tests, CI green, PR"
        " linked to story/task ids, independent review passed.",
    ]
    return "\n".join(lines) + "\n"


def render_asset_files(assets: list | None = None) -> dict[str, object]:
    """The Assets layer of the run's delivery profile, laid out for the pack.

    Returns `assets/<dest> -> body` plus an `assets-manifest.json` naming
    every file with the layer id and version it came from. Bodies are copied
    **verbatim**: an asset is the artifact itself, so nothing is rendered,
    escaped or re-indented on the way through (see `layers.ASSET_LAYERS`).
    An empty Assets layer contributes nothing at all — no manifest, no
    directory — so a profile that supplies no assets publishes exactly what
    it published before this layer existed.
    """
    assets = layers.assets() if assets is None else assets
    if not assets:
        return {}
    out: dict[str, object] = {
        f"assets/{a.dest}": a.body + "\n" for a in assets
    }
    out["assets-manifest.json"] = {
        "count": len(assets),
        "published_root": ".s7/assets",
        "provenance": "rule_based",
        "note": "Reference material supplied with this project; copy from it,"
                " never edit it in place — S7 overwrites .s7/assets on publish.",
        "assets": [
            {
                "id": a.id,
                "title": a.title,
                "summary": a.summary,
                "dest": a.dest,
                "published_to": f".s7/assets/{a.dest}",
                "sha256": a.sha256,
                "source": a.source,
            }
            for a in assets
        ],
    }
    return out


def render_team_pack(
    *,
    run_id: str,
    team: str,
    stories: list[dict],
    tasks: list[dict],
    all_stories: list[dict],
    pack_version: int,
    plan_version: int,
    architecture_version: int,
    assignments: dict[str, str] | None = None,
    default_branch: str = "main",
    stack: str | None = None,
) -> dict[str, object]:
    assignments = assignments or {}
    project_assets = layers.assets()
    slug = team_slug(team)
    repo = next((s.get("target_repository", "") for s in stories), "")
    story_ids = [s["story_id"] for s in stories]
    task_ids = [t["task_id"] for t in tasks]
    deps = dependency_map(all_stories)
    team_deps = [
        p for p in deps["integration_points"]
        if p["from_team"] == team or p["to_team"] == team
    ]
    acs_total = sum(len(s.get("acceptance_criteria", [])) for s in stories)
    pack_md = "\n".join([
        f"# Team delivery pack — {team} (v{pack_version})",
        "",
        f"Run {run_id}. Stories: {', '.join(story_ids)} ({acs_total}"
        f" acceptance criteria). Repository: `{repo}`.",
        "",
        "This pack inherits run-level architecture"
        f" (v{architecture_version}) and the signed plan"
        f" (v{plan_version}) by reference. Layered layout:",
        "",
        "- `AGENTS.md` — developer/coding-agent guidance",
        "- `stories/<story>/` — story context and acceptance criteria",
        "- `tasks/<task>/` — thin task packs referencing canonical artifacts",
        "- `test-strategy.md`, `rollback-guidance.md` — team-level strategy",
        "- `git-workflow.md` — the five developer phrases, the per-criterion"
        " plan the developer edits before it is built, the human"
        " verification each criterion needs, story-owned files, the push"
        " checklist",
        "- `code-conventions.md` — how the code itself is written, and the"
        " rule that this repository's own conventions outrank it",
        "- `ui-guidelines.md` — MapleSure design rules and UI evidence",
        "- `db-conventions.md` — migrations, config fragments and seed data",
        "- `ui/app.css`, `ui/layout.html` — the starter stylesheet and shared"
        " page layout every page copies in",
        "- `workspace-manifest.json` — what the developer workspace receives",
        *([
            "- `assets/` — project artifacts supplied with this delivery"
            f" ({len(project_assets)}), published verbatim to `.s7/assets/`;"
            " reference material to copy from, never to edit in place",
        ] if project_assets else []),
    ]) + "\n"
    readme = "\n".join([
        f"# {team} delivery pack",
        "",
        "Governed engineering context generated by the S7 Delivery Control"
        " Centre. Start with `AGENTS.md`; the canonical architecture is"
        " referenced by version and shipped under `architecture/` in this"
        " download (or `.s7/shared/` when published to the repository).",
    ]) + "\n"
    test_strategy = "\n".join([
        f"# Test strategy — {team}",
        "",
        "- Test-first: the red baseline precedes implementation.",
        "- One executable test per acceptance criterion, named for it.",
        "- Regression: the repository's existing suite must stay green.",
        "- Evidence: test results are collected per task and mapped back to"
        " acceptance criteria in the Control Centre.",
    ]) + "\n"
    rollback_lines = [f"# Rollback guidance — {team}", ""]
    for s in stories:
        flag = s.get("feature_flag") or {}
        rb = s.get("rollback_plan") or {}
        rollback_lines.append(
            f"- {s['story_id']}: flag `{flag.get('name', 'none')}`;"
            f" rollback: {rb.get('method', 'none recorded')}"
        )
    manifest = {
        "workspace": f"{slug}-workspace",
        "run_id": run_id,
        "team": team,
        "team_slug": slug,
        "repository": repo,
        "branch": branch_name(run_id, team),
        "delivery_pack_id": pack_id_for(team),
        "pack_version": pack_version,
        "plan_version": plan_version,
        "architecture_version": architecture_version,
        "stories": story_ids,
        "tasks": task_ids,
        "managed_paths": ["AGENTS.md", ".s7/"],
    }
    return {
        "README.md": readme,
        "team-delivery-pack.md": pack_md,
        "AGENTS.md": render_team_agents_md(
            team, stories, tasks, architecture_version=architecture_version,
            assignments=assignments, assets=project_assets,
        ),
        "assigned-stories.json": {
            "team": team,
            "stories": [
                {
                    "story_id": s["story_id"],
                    "title": s.get("title", ""),
                    "folder": story_folder_name(s),
                    "acceptance_criteria": len(s.get("acceptance_criteria", [])),
                    "assigned_to": assignments.get(s["story_id"], ""),
                }
                for s in stories
            ],
        },
        "team-dependencies.json": {"team": team, "cross_team": team_deps},
        "test-strategy.md": test_strategy,
        "rollback-guidance.md": "\n".join(rollback_lines) + "\n",
        "git-workflow.md": render_git_workflow_md(
            run_id=run_id, team=team, stories=stories,
            default_branch=default_branch,
        ),
        "code-conventions.md": render_code_conventions_md(
            team=team, stories=stories, stack=stack,
        ),
        "ui-guidelines.md": render_ui_guidelines_md(team=team, stories=stories),
        "db-conventions.md": render_db_conventions_md(
            stories=stories, default_branch=default_branch,
        ),
        **render_ui_starter_files(stack=stack),
        **render_asset_files(project_assets),
        "workspace-manifest.json": manifest,
    }
