"""Delivery pack rendering — layered governed context per team (spec §4–§8).

Level 2 (team pack), Level 3 (story pack) and Level 4 (thin task pack) are
rendered here as pure functions; the engine owns storage, versioning,
provenance and phase transitions. Task packs reference canonical artifacts by
version in `context.json` — they never copy architecture.md.

`AGENTS.md` carries the s7-managed marker line: publication refuses to
overwrite an AGENTS.md that lacks it (someone else's file), and developers
can see at a glance that the file is generated, not hand-written.
"""

from __future__ import annotations

from s7_delivery.factory.architecture import dependency_map, team_slug
from s7_delivery.factory.artifact_export import (
    render_acceptance_criteria_md,
    render_agents_md,
    story_folder_name,
)

S7_MARKER = "<!-- s7-managed: generated by the S7 Delivery Control Centre; do not hand-edit -->"

TEAM_FILES = (
    "README.md",
    "team-delivery-pack.md",
    "AGENTS.md",
    "assigned-stories.json",
    "team-dependencies.json",
    "test-strategy.md",
    "rollback-guidance.md",
    "workspace-manifest.json",
)

STORY_FILES = ("story.md", "acceptance-criteria.md", "dependencies.json",
               "story-context.json")

TASK_FILES = ("task.md", "context.json", "test-plan.md", "task-evidence.json")


def pack_id_for(team: str) -> str:
    return f"PACK-{team_slug(team)}"


def branch_name(run_id: str, team: str) -> str:
    """Fresh, disposable context branch — unique per run and team, and never
    a default branch name by construction."""
    return f"s7/{run_id.lower()}-{team_slug(team)}"


# --- Level 3: story pack ----------------------------------------------------


def render_story_pack(story: dict, *, plan_version: int,
                      architecture_version: int) -> dict[str, object]:
    return {
        "story.md": render_agents_md(story),
        "acceptance-criteria.md": render_acceptance_criteria_md(story),
        "dependencies.json": {
            "story_id": story["story_id"],
            "depends_on": story.get("dependencies", []),
        },
        "story-context.json": {
            "story_id": story["story_id"],
            "epic_id": story.get("epic_id", ""),
            "plan_version": plan_version,
            "architecture_version": architecture_version,
            "accountable_team": story.get("accountable_team", ""),
            "repository": story.get("target_repository", ""),
            "acceptance_criteria": [
                ac["ac_id"] for ac in story.get("acceptance_criteria", [])
            ],
        },
    }


# --- Level 4: thin task pack ------------------------------------------------


def render_task_pack(task: dict, story: dict, *, plan_version: int,
                     architecture_version: int,
                     team_pack_version: int) -> dict[str, object]:
    acs = [ac["ac_id"] for ac in story.get("acceptance_criteria", [])]
    task_md = "\n".join([
        f"# {task['task_id']} — {task.get('summary', '')}",
        "",
        f"Story: {task['story_id']} — {story.get('title', '')}",
        f"Accountable team: {task.get('accountable_team', '')}",
        "",
        "## Goal",
        story.get("purpose", ""),
        "",
        "## Acceptance criteria in scope",
        *[f"- {ac_id}" for ac_id in acs],
        "",
        "Canonical context: see `context.json` — architecture and plan are"
        " referenced by version, not copied.",
    ]) + "\n"
    test_plan = "\n".join([
        f"# Test plan — {task['task_id']}",
        "",
        "Every acceptance criterion must have linked executable evidence.",
        "",
        *[f"- [ ] {ac['ac_id']}: covered by a test that fails before the"
          f" change and passes after ({ac['text']})"
          for ac in story.get("acceptance_criteria", [])],
    ]) + "\n"
    return {
        "task.md": task_md,
        "context.json": {
            "task_id": task["task_id"],
            "story_id": task["story_id"],
            "plan_version": plan_version,
            "architecture_version": architecture_version,
            "team_pack_version": team_pack_version,
            "acceptance_criteria": acs,
            "dependencies": task.get("dependencies", []),
        },
        "test-plan.md": test_plan,
        "task-evidence.json": {
            "task_id": task["task_id"],
            "status": task.get("status", "not_started"),
            "commit_ref": task.get("commit_ref", ""),
            "pr_ref": task.get("pr_ref", ""),
            "ci_status": task.get("ci_status", ""),
        },
    }


# --- Level 2: team pack -----------------------------------------------------


def render_team_agents_md(team: str, stories: list[dict], tasks: list[dict],
                          *, architecture_version: int,
                          assignments: dict[str, str] | None = None) -> str:
    """Developer/coding-agent guidance (spec §14). The developer owns
    implementation; a coding assistant may help — S7 provides the context."""
    assignments = assignments or {}
    story_ids = [s["story_id"] for s in stories]
    components = sorted(
        {s.get("target_component", "") for s in stories if s.get("target_component")}
    )
    lines = [
        S7_MARKER,
        f"# {team} — delivery context",
        "",
        "## Application Context",
        f"MapleSure group benefits. Architecture v{architecture_version} in"
        " `.s7/shared/architecture.md` is canonical for boundaries and data"
        " flow; the repository's own `architecture.md` stays authoritative"
        " for local detail.",
        "",
        "## Current Delivery Context",
        *[f"- {s['story_id']}: {s.get('title', '')}" for s in stories],
        *[f"- {t['task_id']} → {t['story_id']}: {t.get('summary', '')}"
          for t in tasks],
        "",
        "## Story Assignments",
        "Assignment is a human decision made in the S7 Control Centre —"
        " canonical copy in `.s7/shared/assigned-stories.json`.",
        *[
            f"- {s['story_id']} ({s.get('title', '')}): "
            + (f"assigned to {assignments[s['story_id']]}"
               if assignments.get(s["story_id"]) else "unassigned")
            for s in stories
        ],
        "",
        '## Coding Agent: "What is assigned to me?"',
        "When a developer asks what they should work on: read"
        " `.s7/shared/assigned-stories.json`, match their name against"
        " `assigned_to`, then open `.s7/stories/<story>/` for that story —"
        " `story.md` for context, `acceptance-criteria.md` for the checklist,"
        " and `.s7/tasks/<task>/` for the executable task packs. Summarise"
        " the story and its acceptance criteria before implementing, and"
        " implement only within Allowed Components under the Engineering"
        " Rules below. If no story carries their name, say so — never guess"
        " an assignment.",
        "",
        "## Architecture Rules",
        "Respect the integration boundaries in"
        " `.s7/shared/architecture.md`; consume other applications only"
        " through their published interfaces.",
        "",
        "## Engineering Rules",
        "See `.s7/shared/engineering-rules.md` — scope discipline,"
        " test-first, traceability, no self-approval.",
        "",
        "## Acceptance Criteria",
        "Per story under `.s7/stories/<story>/acceptance-criteria.md`."
        " Every criterion needs linked executable evidence.",
        "",
        "## Testing Rules",
        "Write the failing test first; record the red baseline; a criterion"
        " without a test is not done.",
        "",
        "## Scope Boundaries",
        f"This pack covers {', '.join(story_ids)} only.",
        "",
        "## Allowed Components",
        *[f"- {c}" for c in components],
        "- associated tests",
        "",
        "## Out-of-Scope Components",
        "Everything not listed above — a change outside scope needs a new"
        " ticket, not a bigger diff.",
        "",
        "## Security / Compliance Constraints",
        "Synthetic data only; no PII in code, fixtures or logs; no shared"
        " credentials.",
        "",
        "## Rollback Expectations",
        "Feature flags and the story rollback plans in"
        " `rollback-guidance.md` must be wired before release.",
        "",
        "## Completion Conditions",
        "All acceptance criteria evidenced by passing tests, CI green, PR"
        " linked to story/task ids, independent review passed.",
    ]
    return "\n".join(lines) + "\n"


def render_team_pack(
    *,
    run_id: str,
    team: str,
    stories: list[dict],
    tasks: list[dict],
    all_stories: list[dict],
    pack_version: int,
    plan_version: int,
    architecture_version: int,
    assignments: dict[str, str] | None = None,
) -> dict[str, object]:
    assignments = assignments or {}
    slug = team_slug(team)
    repo = next((s.get("target_repository", "") for s in stories), "")
    story_ids = [s["story_id"] for s in stories]
    task_ids = [t["task_id"] for t in tasks]
    deps = dependency_map(all_stories)
    team_deps = [
        p for p in deps["integration_points"]
        if p["from_team"] == team or p["to_team"] == team
    ]
    acs_total = sum(len(s.get("acceptance_criteria", [])) for s in stories)
    pack_md = "\n".join([
        f"# Team delivery pack — {team} (v{pack_version})",
        "",
        f"Run {run_id}. Stories: {', '.join(story_ids)} ({acs_total}"
        f" acceptance criteria). Repository: `{repo}`.",
        "",
        "This pack inherits run-level architecture"
        f" (v{architecture_version}) and the signed plan"
        f" (v{plan_version}) by reference. Layered layout:",
        "",
        "- `AGENTS.md` — developer/coding-agent guidance",
        "- `stories/<story>/` — story context and acceptance criteria",
        "- `tasks/<task>/` — thin task packs referencing canonical artifacts",
        "- `test-strategy.md`, `rollback-guidance.md` — team-level strategy",
        "- `workspace-manifest.json` — what the developer workspace receives",
    ]) + "\n"
    readme = "\n".join([
        f"# {team} delivery pack",
        "",
        "Governed engineering context generated by the S7 Delivery Control"
        " Centre. Start with `AGENTS.md`; the canonical architecture is"
        " referenced by version and shipped under `architecture/` in this"
        " download (or `.s7/shared/` when published to the repository).",
    ]) + "\n"
    test_strategy = "\n".join([
        f"# Test strategy — {team}",
        "",
        "- Test-first: the red baseline precedes implementation.",
        "- One executable test per acceptance criterion, named for it.",
        "- Regression: the repository's existing suite must stay green.",
        "- Evidence: test results are collected per task and mapped back to"
        " acceptance criteria in the Control Centre.",
    ]) + "\n"
    rollback_lines = [f"# Rollback guidance — {team}", ""]
    for s in stories:
        flag = s.get("feature_flag") or {}
        rb = s.get("rollback_plan") or {}
        rollback_lines.append(
            f"- {s['story_id']}: flag `{flag.get('name', 'none')}`;"
            f" rollback: {rb.get('method', 'none recorded')}"
        )
    manifest = {
        "workspace": f"{slug}-workspace",
        "run_id": run_id,
        "team": team,
        "team_slug": slug,
        "repository": repo,
        "branch": branch_name(run_id, team),
        "delivery_pack_id": pack_id_for(team),
        "pack_version": pack_version,
        "plan_version": plan_version,
        "architecture_version": architecture_version,
        "stories": story_ids,
        "tasks": task_ids,
        "managed_paths": ["AGENTS.md", ".s7/"],
    }
    return {
        "README.md": readme,
        "team-delivery-pack.md": pack_md,
        "AGENTS.md": render_team_agents_md(
            team, stories, tasks, architecture_version=architecture_version,
            assignments=assignments,
        ),
        "assigned-stories.json": {
            "team": team,
            "stories": [
                {
                    "story_id": s["story_id"],
                    "title": s.get("title", ""),
                    "folder": story_folder_name(s),
                    "acceptance_criteria": len(s.get("acceptance_criteria", [])),
                    "assigned_to": assignments.get(s["story_id"], ""),
                }
                for s in stories
            ],
        },
        "team-dependencies.json": {"team": team, "cross_team": team_deps},
        "test-strategy.md": test_strategy,
        "rollback-guidance.md": "\n".join(rollback_lines) + "\n",
        "workspace-manifest.json": manifest,
    }
