"""Rule-based test skeletons derived from acceptance criteria.

Deterministic and non-AI by design: the skeleton is a red baseline —
one failing test per acceptance criterion — that publishes with the
delivery pack so the developer starts from real red and CI evidence
joins per-AC by test name. Badged RULE_BASED wherever shown; presenting
a heuristic as AI output is the mislabelling CLAUDE.md § Staged output
forbids. Name derivation is shared with simulate.py so simulated and
real evidence always agree on names.
"""

from __future__ import annotations

from pathlib import Path

from s7_delivery.factory.models import now_iso

RULE_BASED = "rule_based"


def slug_test_name(text: str) -> str:
    """`test_<slug>` from AC text — the single source of truth for
    AC-derived test names (simulate.py delegates here)."""
    slug = "".join(c if c.isalnum() else "_" for c in text.lower())[:48].strip("_")
    while "__" in slug:
        slug = slug.replace("__", "_")
    return f"test_{slug}"


def _story_slug(story_id: str) -> str:
    return story_id.lower().replace("-", "_")


def pytest_file_name(story_id: str) -> str:
    return f"test_{_story_slug(story_id)}.py"


def render_pytest(story: dict) -> dict[str, str]:
    """One pytest file per story, one deliberately-failing test per AC."""
    lines = [
        f'"""Acceptance tests for {story["story_id"]} — {story.get("title", "")}',
        "",
        "Generated by S7 (rule-based) as the red baseline. Implement the",
        "behaviour, then replace each pytest.fail with real assertions —",
        "keep the test names: CI evidence joins to acceptance criteria by",
        'name."""',
        "import pytest",
        "",
    ]
    for ac in story.get("acceptance_criteria", []):
        lines += [
            "",
            f"def {slug_test_name(ac['text'])}():",
            f'    """{ac["ac_id"]}: {ac["text"]}"""',
            f'    pytest.fail("Not implemented: {ac["ac_id"]}")',
        ]
    return {pytest_file_name(story["story_id"]): "\n".join(lines) + "\n"}


def junit_class_name(story_id: str) -> str:
    return "".join(p for p in story_id.split("-") if p) + "AcceptanceTest"


def render_junit(story: dict) -> dict[str, str]:
    """One JUnit 5 class per story, package `s7`, one failing @Test per AC.
    Method names deliberately match the pytest names (snake_case) so CI
    evidence joins per-AC identically on both stacks."""
    name = junit_class_name(story["story_id"])
    lines = [
        "package s7;",
        "",
        "import org.junit.jupiter.api.Test;",
        "import static org.junit.jupiter.api.Assertions.fail;",
        "",
        f"/** Acceptance tests for {story['story_id']} — {story.get('title', '')}.",
        " * Generated by S7 (rule-based) as the red baseline. Implement the",
        " * behaviour, then replace each fail(...) with real assertions —",
        " * keep the method names: CI evidence joins to acceptance criteria",
        " * by name. */",
        f"class {name} {{",
    ]
    for ac in story.get("acceptance_criteria", []):
        lines += [
            "",
            "    @Test",
            f"    void {slug_test_name(ac['text'])}() {{",
            f"        // {ac['ac_id']}: {ac['text']}",
            f'        fail("Not implemented: {ac["ac_id"]}");',
            "    }",
        ]
    lines += ["}", ""]
    return {f"{name}.java": "\n".join(lines)}


def runnable_root(stack: str) -> str:
    return {"pytest": "tests/s7", "maven": "src/test/java/s7"}[stack]


def resolve_stack(repo: dict | None, repo_dir: Path | None) -> str | None:
    """The connected repo's stack: the bootstrap record first (it already
    made this call at connect time), file detection second, None when
    neither knows — never a guess."""
    status = (repo or {}).get("ci_bootstrap_status", "")
    if status.startswith("bootstrapped:"):
        stack = status.split(":", 1)[1]
        return stack if stack in ("pytest", "maven") else None
    if repo_dir is not None and Path(repo_dir).is_dir():
        from s7_delivery.factory.ci_bootstrap import detect_stack_from_files
        return detect_stack_from_files(Path(repo_dir))
    return None


def render_story_tests(story: dict, stack: str | None) -> tuple[dict[str, str], dict]:
    """(files, manifest) for one story. Unknown stacks still render
    pytest-style files, marked non-runnable (reference only)."""
    runnable = stack in ("pytest", "maven")
    files = render_junit(story) if stack == "maven" else render_pytest(story)
    manifest = {
        "story_id": story["story_id"],
        "stack": stack or "",
        "runnable": runnable,
        "provenance": RULE_BASED,
        "generated_at": now_iso(),
        "tests": [
            {
                "ac_id": ac["ac_id"],
                "test_name": slug_test_name(ac["text"]),
                "file": next(iter(files)),
            }
            for ac in story.get("acceptance_criteria", [])
        ],
    }
    return files, manifest
