"""Rule-based test skeletons derived from acceptance criteria.

Deterministic and non-AI by design: the skeleton is a red baseline —
one failing test per acceptance criterion — that publishes with the
delivery pack so the developer starts from real red and CI evidence
joins per-AC by test name. Badged RULE_BASED wherever shown; presenting
a heuristic as AI output is the mislabelling CLAUDE.md § Staged output
forbids. Name derivation is shared with simulate.py so simulated and
real evidence always agree on names.
"""

from __future__ import annotations

from pathlib import Path

RULE_BASED = "rule_based"

# The two scripted names the simulated demo depends on. They live here, not in
# simulate.py, because this module is the single naming authority: the rendered
# skeletons, the manifest and the simulated TestCaseRecords must agree on every
# name or CI evidence cannot join per-AC.
_SCRIPTED_NAMES = {
    "US-003-AC2": "test_accepts_first_day_absent_after_last_day_worked",
    # The defective first version only checks strictly-before — the name
    # honestly reflects what it asserts, which is how the reviewer spots it.
    "US-003-AC3": "test_rejects_first_day_absent_before_last_day_worked",
}


def slug_test_name(text: str) -> str:
    """`test_<slug>` from AC text — the single source of truth for
    AC-derived test names (simulate.py delegates here)."""
    slug = "".join(c if c.isalnum() else "_" for c in text.lower())[:48].strip("_")
    while "__" in slug:
        slug = slug.replace("__", "_")
    return f"test_{slug}"


def test_name_for(story: dict, ac: dict) -> str:
    """The name of the test that evidences one acceptance criterion.

    The scripted overrides apply only to the engine's own seeded (SIMULATED)
    stories — a HUMAN story that happens to reuse a seeded id must not inherit
    the deliberate US-003 misnaming."""
    if story.get("provenance", "simulated") == "simulated":
        override = _SCRIPTED_NAMES.get(ac.get("ac_id", ""))
        if override:
            return override
    return slug_test_name(ac.get("text", ""))


def dedupe_names(names: list[str]) -> list[str]:
    """Two acceptance criteria can slug to the same name (identical prefixes
    inside the 48-char window). Suffix duplicates deterministically so the
    rendered file compiles and the per-AC join stays one-to-one."""
    used: set[str] = set()
    out: list[str] = []
    for name in names:
        candidate, n = name, 1
        while candidate in used:
            n += 1
            candidate = f"{name}_{n}"
        used.add(candidate)
        out.append(candidate)
    return out


def story_test_names(story: dict) -> list[str]:
    """One unique test name per acceptance criterion, in criterion order."""
    return dedupe_names(
        [test_name_for(story, ac) for ac in story.get("acceptance_criteria", [])]
    )


def _flat(text: str) -> str:
    """Author-supplied AC text is free-form and may carry newlines: collapse
    it to one line before it is embedded in a docstring or a // comment."""
    return " ".join(str(text).split())


def _py_safe(text: str) -> str:
    """AC text that cannot break out of a Python docstring."""
    return _flat(text).replace("\\", "/").replace('"""', "'''")


def _java_safe(text: str) -> str:
    """AC text that cannot close a Java block comment."""
    return _flat(text).replace("*/", "* /")


def _story_slug(story_id: str) -> str:
    return story_id.lower().replace("-", "_")


def pytest_file_name(story_id: str) -> str:
    return f"test_{_story_slug(story_id)}.py"


def render_pytest(story: dict) -> dict[str, str]:
    """One pytest file per story, one deliberately-failing test per AC."""
    lines = [
        f'"""Acceptance tests for {story["story_id"]} — {_py_safe(story.get("title", ""))}',
        "",
        "Generated by S7 (rule-based) as the red baseline. Implement the",
        "behaviour, then replace each pytest.fail with real assertions —",
        "keep the test names: CI evidence joins to acceptance criteria by",
        'name."""',
        "import pytest",
        "",
    ]
    for ac, name in zip(story.get("acceptance_criteria", []), story_test_names(story)):
        lines += [
            "",
            f"def {name}():",
            f'    """{ac["ac_id"]}: {_py_safe(ac["text"])}"""',
            f'    pytest.fail("Not implemented: {ac["ac_id"]}")',
        ]
    return {pytest_file_name(story["story_id"]): "\n".join(lines) + "\n"}


def junit_class_name(story_id: str) -> str:
    return "".join(p for p in story_id.split("-") if p) + "AcceptanceTest"


def render_junit(story: dict) -> dict[str, str]:
    """One JUnit 5 class per story, package `s7`, one failing @Test per AC.
    Method names deliberately match the pytest names (snake_case) so CI
    evidence joins per-AC identically on both stacks."""
    name = junit_class_name(story["story_id"])
    lines = [
        "package s7;",
        "",
        "import org.junit.jupiter.api.Test;",
        "import static org.junit.jupiter.api.Assertions.fail;",
        "",
        f"/** Acceptance tests for {story['story_id']} — {_java_safe(story.get('title', ''))}.",
        " * Generated by S7 (rule-based) as the red baseline. Implement the",
        " * behaviour, then replace each fail(...) with real assertions —",
        " * keep the method names: CI evidence joins to acceptance criteria",
        " * by name. */",
        f"class {name} {{",
    ]
    for ac, method in zip(story.get("acceptance_criteria", []), story_test_names(story)):
        lines += [
            "",
            "    @Test",
            f"    void {method}() {{",
            f"        // {ac['ac_id']}: {_java_safe(ac['text'])}",
            f'        fail("Not implemented: {ac["ac_id"]}");',
            "    }",
        ]
    lines += ["}", ""]
    return {f"{name}.java": "\n".join(lines)}


def runnable_root(stack: str) -> str:
    return {"pytest": "tests/s7", "maven": "src/test/java/s7"}[stack]


def resolve_stack(repo: dict | None, repo_dir: Path | None) -> str | None:
    """The connected repo's stack: the bootstrap record first (it already
    made this call at connect time), file detection second, None when
    neither knows — never a guess."""
    status = (repo or {}).get("ci_bootstrap_status", "")
    if status.startswith("bootstrapped:"):
        stack = status.split(":", 1)[1]
        return stack if stack in ("pytest", "maven") else None
    if repo_dir is not None and Path(repo_dir).is_dir():
        from s7_delivery.factory.ci_bootstrap import detect_stack_from_files
        return detect_stack_from_files(Path(repo_dir))
    return None


def render_story_tests(story: dict, stack: str | None) -> tuple[dict[str, str], dict]:
    """(files, manifest) for one story. Unknown stacks still render
    pytest-style files, marked non-runnable (reference only)."""
    runnable = stack in ("pytest", "maven")
    files = render_junit(story) if stack == "maven" else render_pytest(story)
    # Deliberately no generated_at: identical inputs must produce identical
    # bytes, or a regeneration that changed nothing still reads as a change
    # (and republishes a "new" pack).
    manifest = {
        "story_id": story["story_id"],
        "stack": stack or "",
        "runnable": runnable,
        "provenance": RULE_BASED,
        "tests": [
            {
                "ac_id": ac["ac_id"],
                "test_name": name,
                "file": next(iter(files)),
            }
            for ac, name in zip(
                story.get("acceptance_criteria", []), story_test_names(story)
            )
        ],
    }
    return files, manifest
